name: Deploy to Portainer

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Docker image
        run: docker build --network=host -t ghcr.io/lyttledevelopment/furmin-bot:main -f Dockerfile .

      - name: Push API Docker image to GitHub Container Registry
        run: docker push ghcr.io/lyttledevelopment/furmin-bot:main

  trigger-portainer-webhook:
    name: Trigger Portainer Webhook
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Call Portainer Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          method: POST